blogs/urls.py
from django.urls import path
from .views import PostListView, PostCreateView, PostDetailView, PostUpdateView

blogs_patterns = ([
    path('', PostListView.as_view(), name='posts'),
    path('create/<int:combate>', PostCreateView.as_view(), name='create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
], 'blogs')

boxeadores/urls.py
from django.urls import path
from .views import BoxeadorListView, BoxeadorCreateView, BoxeadorUpdateView, BoxeadorDeleteView, BoxeadorDetailView
from .views import buscar, AsociacionMundialCreateView, CategoriaCreateView, CategoriaListView, CategoriaUpdateView

# BOXEADORES 

boxeadores_patterns = ([
    path('', BoxeadorListView.as_view(), name='boxeadores'),
    path('alta', BoxeadorCreateView.as_view(), name='alta'),
    path('ver/<int:pk>/', BoxeadorDetailView.as_view(), name='ver'),
    path('modifica/<int:pk>/', BoxeadorUpdateView.as_view(), name='modifica'),
    path('eliminar/<int:pk>/', BoxeadorDeleteView.as_view(), name='eliminar'),

    path('alta', AsociacionMundialCreateView.as_view(), name='alta'),

    path("buscar/", buscar, name="buscar"),

], 'boxeadores')

# ASOCIACIONES

asociaciones_patterns = ([
    path('alta', AsociacionMundialCreateView.as_view(), name='alta'),
], 'asociaciones')

# CATEGORIAS

categorias_patterns = ([
    path('', CategoriaListView.as_view(), name='categorias'),
    path('alta', CategoriaCreateView.as_view(), name='alta'),
    path('modifica/<int:pk>/', CategoriaUpdateView.as_view(), name='modifica'),
], 'categorias')

elRing/urls.py
from django.contrib import admin
from django.urls import path, include
from boxeadores.urls import boxeadores_patterns, asociaciones_patterns, categorias_patterns
from combates.urls import combates_patterns
from profiles.urls import profiles_patterns
from blogs.urls import blogs_patterns
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('centro.urls')),
    path('boxeadores/', include(boxeadores_patterns)),
    path('combates/', include(combates_patterns)),
    path('profiles/', include(profiles_patterns)),
    path('asociaciones/', include(asociaciones_patterns)),
    path('categorias/', include(categorias_patterns)),
    path('blogs/', include(blogs_patterns)),
    

    # Autenticacion
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

boxeadores/models.py
from django.db import models
from django.apps import apps
from django.db.models import Q

PROFESIONAL = "P"
AMATEUR = "A"

ESTADO = ((PROFESIONAL, "Profesional"), (AMATEUR, "Amateur"))

MALE = "M"
FEMALE = "F"

GENERO = ((MALE, "Masculino"), (FEMALE, "Femenino"))


class AsociacionMundial(models.Model):

    siglas = models.CharField(max_length=5)
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Asociacion Mundial"
        verbose_name_plural = "Asociaciones Mundiales"

    def __str__(self):
        return "%s"  %(self.nombre)


class AsociacionContinental(models.Model):

    siglas = models.CharField(max_length=5)
    nombre = models.CharField(max_length=50)


class AsosiacionLocal(models.Model):

    siglas = models.CharField(max_length=5)
    nombre = models.CharField(max_length=50)
    anexo = models.TextField(blank=True)

    class Meta:
        verbose_name = "AsosiacionLocal"

    def __str__(self):
        pass


class Categoria(models.Model):

    nombre = models.CharField(max_length=50)
    libras = models.IntegerField(default=0)
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = ['-libras']

    def __str__(self):
        return self.nombre

    def save(self):
        for atr in ["nombre"]:
            self.__setattr__(atr, self.__getattribute__(atr).upper())
        super().save()

    def libras_a_kilos(self):
        return "{0:.2f}".format(self.libras/2.2046)
        

class Boxeador(models.Model):

    apellido = models.CharField(max_length=50)
    nombre = models.CharField(max_length=50)
    alias = models.CharField(max_length=50)
    imagen = models.ImageField(verbose_name="Imagen", upload_to="projects")
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE)
    genero = models.CharField(
        max_length=3, choices=GENERO, default=MALE)
    estado = models.CharField(
        max_length=3, choices=ESTADO, default=PROFESIONAL)

    class Meta:
        verbose_name = "Boxeador"
        verbose_name_plural = "Boxeadores"

    def save(self):
        for atr in ["apellido", "nombre", "alias"]:
            self.__setattr__(atr, self.__getattribute__(atr).upper())
        super().save()

    def __str__(self):
        return "%s %s (%s)" % (self.apellido, self.nombre, self.alias)

    def lista_combates(self):
        combate = apps.get_model('combates.Combate').objects.filter(
            Q(luchador_id=self.id)
            | Q(oponente_id=self.id))
        
        return combate

    def last_five_fights(self):
        return self.lista_combates().order_by('-fecha')[1:5]


class Boxeador_Categoria(models.Model):
    boxeador = models.ForeignKey(Boxeador, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    fecha_modificacion = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("boxeador", "categoria")


class Record(models.Model):
    boxeador = models.OneToOneField(Boxeador,on_delete=models.CASCADE)
    total = models.IntegerField(default=0)
    ganado = models.IntegerField(default=0)
    ganado_ko = models.IntegerField(default=0)
    perdido = models.IntegerField(default=0)
    perdido_ko = models.IntegerField(default=0)
    empate = models.IntegerField(default=0)

    def alta(self, luchador:None, ko:None, ganador:None, empate:None):
        try:
            self = Record.objects.get(boxeador_id=luchador)
        except Record.DoesNotExist:
            self.boxeador_id = luchador
        if empate:
            self.empate = self.empate + 1
        else:
            if ganador:
                if luchador == ganador.id:
                    self.ganado = self.ganado + 1
                    if ko:
                        self.ganado_ko = self.ganado_ko + 1
                else:
                    self.perdido = self.perdido + 1
                    if ko:
                        self.perdido_ko = self.perdido_ko + 1
        self.total = self.ganado + self.perdido + self.empate
        self.save()
        

    def baja(self, luchador:None, ko:None, ganador:None, empate:None):
        self = Record.objects.get(boxeador_id=luchador.id)
        if empate:
            self.empate = self.empate - 1
        else:
            if ganador:
                if luchador.id == ganador.id:
                    self.ganado = self.ganado - 1
                    if ko:
                        self.ganado_ko = self.ganado_ko - 1
                else:
                    self.perdido = self.perdido - 1
                    if ko:
                        self.perdido_ko = self.perdido_ko - 1        
        self.total = self.ganado + self.perdido + self.empate
        self.save()

    def __str__(self):
        return "%s"  %(self.boxeador)
        

# Create your models here.

boxeadores/forms.py
from django import forms
from .models import Boxeador, AsociacionMundial, Categoria
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


class BoxeadorForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):

    class Meta:
        model = Boxeador
        fields = ('apellido', 'nombre', 'alias', 'categoria', 'genero', 'estado', 'imagen',)
        widgets = {
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Apellido'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'alias': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Alias'}),
            'categoria': forms.Select(attrs={"class": "form-control"}),
            'genero': forms.Select(attrs={"class": "form-control"}),
            'estado': forms.Select(attrs={"class": "form-control"}),
        }
        labels = {
            'apellido': '', 'nombre': '', 'alias': '', 'categoria': '', 'genero':'', 'estado':'',
        }

class AsociacionMundialForm(forms.ModelForm):
    class Meta:
        model = AsociacionMundial
        fields = ('siglas', 'nombre',)

class CategoriaForm(PopRequestMixin, CreateUpdateAjaxMixin, forms.ModelForm):
    class Meta:
        model = Categoria
        fields = ('nombre', 'libras')
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nombre'}),
            'libras': forms.NumberInput(attrs={"class": "form-control"})
        }
        labels = {
            'nombre':'', 'libras':''
        }

boxeadores/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from .models import Boxeador, Categoria, ESTADO, Record, Categoria
from .models import AsociacionMundial
from .forms import BoxeadorForm, AsociacionMundialForm, CategoriaForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from bootstrap_modal_forms.mixins import PassRequestMixin
from combates.models import Combate
from django.db.models import Q
from django.http import JsonResponse


class BoxeadorListView(ListView):
    model = Boxeador
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Boxeadores'
        context['estados'] = ESTADO
        context['categorias'] = Categoria.objects.values()
        if self.request.GET.get('categoria', ''):
            context['categoria'] = int(self.request.GET.get('categoria', ''))
        context['texto'] = self.request.GET.get('texto', '')
        return context

    def get_queryset(self):
        boxeador = self.model.objects.all().select_related('categoria')
        categoria = self.request.GET.get('categoria', '0')
        texto = self.request.GET.get('texto', '')
        if categoria != '0':
            boxeador = boxeador.filter(categoria_id=categoria).select_related('categoria')
        if texto:
            texto = texto.upper()
            boxeador = boxeador.filter(Q(apellido__contains=texto)
                | Q(nombre__contains=texto)
                | Q(alias__contains=texto)).select_related('categoria')
        return boxeador


class BoxeadorDetailView(DetailView):
    model = Boxeador
    template_name = "boxeadores/boxeador_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Combate'
        return context
    
    def get_queryset(self):
        boxeador = super().get_queryset().select_related('categoria')
        return boxeador

    
class BoxeadorCreateView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Boxeador
    form_class = BoxeadorForm
    template_name = "centro/agregar_modificar_modal.html"
    success_url = reverse_lazy('boxeadores:boxeadores')
    success_message = "Datos guardados exitosamente."


class BoxeadorUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Boxeador
    form_class = BoxeadorForm
    template_name = "centro/agregar_modificar_modal.html"
    success_url = reverse_lazy('boxeadores:boxeadores')
    success_message = "Datos guardados exitosamente."


class BoxeadorDeleteView(SuccessMessageMixin, DeleteView):
    model = Boxeador
    template_name = 'centro/eliminar_modal.html'
    success_url = reverse_lazy('boxeadores:boxeadores')
    success_message = "Datos eliminados exitosamente."

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(BoxeadorDeleteView, self).delete(request, *args, **kwargs)



class AsociacionMundialCreateView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = AsociacionMundial
    form_class = AsociacionMundialForm
    template_name = "boxeadores/asociacionmundial_form.html"
    


class CategoriaListView(ListView):
    model = Categoria
    paginate_by = 20
    



class CategoriaCreateView(PassRequestMixin, SuccessMessageMixin, CreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = "centro/agregar_modificar_modal.html"
    success_url = reverse_lazy('categorias:categorias')
    success_message = "Datos guardados exitosamente."


class CategoriaUpdateView(PassRequestMixin, SuccessMessageMixin, UpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = "centro/agregar_modificar_modal.html"
    success_url = reverse_lazy('categorias:categorias')
    success_message = "Datos guardados exitosamente."



def buscar(request):
    term = request.GET.get("term", "")
    if term:
        if Boxeador.objects.filter(Q(nombre__contains=term.upper()) | Q(apellido__contains=term.upper())).exists():
            boxeador = Boxeador.objects.filter(Q(nombre__contains=term.upper()) | Q(apellido__contains=term.upper()))
        else:
            boxeador = []
    response = list()
    for b in boxeador:
        response.append(
            {
                "id": b.id,
                "value": "{} {} ({})".format(b.apellido, b.nombre, b.alias),
            }
        )
    return JsonResponse(response, safe=False)



# Create your views here.

boxeadores/templates/boxeadores/asociacionmundial_form.html
{% extends 'centro/base.html' %}
{% load static %}

{% block contenido %}
{% include 'combates/includes/ckeditor.html' %}
<div class="container">
  <div class="row mt-3 mb-5">
    <div class="col-md-9 mx-auto">
        <div class="md-form">
              
      <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        
        {% for error in form.non_field_errors%}
          <div class="alert alert-danger" role="alert">
                {{error}}
          </div>
        {% endfor%}

        {% for field in form  %}
            {% if field == form.luchador %}
                <div class="form-group col-md-12 {% if form.luchador.errors %} invalid has-error {% endif %}">
                    <label for="{{ form.luchador.id_for_label }}" class="control-label">{{ form.luchador.label }}</label>
                    <input autofocus type="search" id="search" class="form-control" 
                    value="{% if form.instance.luchador %} {{form.instance.luchador}} {% endif %}">
                    <input type="hidden" id="luchador" name="luchador" value="{{form.instance.luchador.id}}">
                    {% for error in form.luchador.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% elif field == form.oponente %} 
                <div class="form-group col-md-12 {% if form.oponente.errors %} invalid has-error {% endif %}">
                    <label for="{{ form.oponente.id_for_label }}" class="control-label">{{ form.oponente.label }}</label>
                    <input autofocus type="search" id="search-oponente" class="form-control" 
                    value="{% if form.instance.oponente %} {{form.instance.oponente}} {% endif %}">
                    <input type="hidden" id="oponente" name="oponente" value="{{form.instance.oponente.id}}">
                        {% for error in form.oponente.errors %}
                            <p class="help-block">{{ error }}</p>
                        {% endfor %}
                </div>

            {% elif field == form.ganador %} 
                <div class="form-group col-md-12 {% if form.ganador.errors %} invalid has-error {% endif %}">
                    <label for="{{ form.ganador.id_for_label }}" class="control-label">{{ form.ganador.label }}</label>
                    <input autofocus type="search" id="search-ganador" class="form-control" 
                    value="{% if form.instance.ganador %} {{form.instance.ganador}} {% endif %}">
                    <input type="hidden" id="ganador" name="ganador" value="{{form.instance.ganador.id}}">
                        {% for error in form.ganador.errors %}
                            <p class="help-block">{{ error }}</p>
                        {% endfor %}
                </div>

            {% elif field == form.empate or field == form.knockout%} 
                <div class="form-check">
                {% if field.errors %}
                    <div class="control-group has-error">
                        <label class="control-label"> {{field.label}} </label>
                            <div class="controls"> {{ field }}
                                <span class="help-block">
                                    {% for error in  field.errors %}{{ error }}{% endfor %}
                            </span>
                        </div>
                    </div>
                {% else %}
        
                    {{field}}
                    <label class="form-check-label">{{field.label}}</label>
                        {% if field.help_text %}
                            <p class="help-block"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    
                {% endif %}
            </div>
            

            {% else %}
                <div class="form-group col-md-12">
                    {% if field.errors %}
                        <div class="control-group has-error">
                            <label class="control-label"> {{field.label}} </label>
                                <div class="controls"> {{ field }}
                                    <span class="help-block">
                                        {% for error in  field.errors %}{{ error }}{% endfor %}
                                </span>
                            </div>
                        </div>
                    {% else %}
                        <div class="control-group">
                            <label class="control-label">{{field.label}}</label>
                            <div class="controls">{{field}}
                                {% if field.help_text %}
                                    <p class="help-block"><small>{{ field.help_text }}</small></p>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor  %}  
        <div class="col-md-12">
            <div class="float-right mt-2">
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-sm btn-secondary">Cancelar</a>
                <input type="submit" class="btn btn-primary btn-sm text-rigth" value="Guardar" />
            </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock contenido %}

boxeadores/templates/boxeadores/boxeador_detail.html
{% extends 'centro/base.html' %}
{% load static %}
{% block title %} {{titulo}} {% endblock %}
{% block contenido %}

<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-4 mx-auto">
        <h3 class="section-heading mb-4">{{object.alias}}</h3>
        <div>
          <ul class="list-unstyled">
              <li><b>Apellido y Nombre: </b>{{boxeador.apellido}} {{boxeador.nombre}}</li>
              <li><b>Cantidad de Peleas: </b> {{boxeador.record.total}}</li>
              <li><b>Categoria Actual: </b>{{boxeador.categoria.nombre}}</li>
          {% if perms.boxeadores.change_boxeador %}
            <a class="modificar-modal accion text-primary" title="Modificar Boxeador" data-id="{% url 'boxeadores:modifica' boxeador.id %}">

              Editar
            </a>
            {% endif %}
          </ul>
        </div>
      </div>
      <div class="col-md-4 mx-auto">
          <h3 class="section-heading mb-4">Record</h3>
        <ul class="list-unstyled">
          <li>Cantidad de Combates Ganados: <b class="text-primary">{{boxeador.record.ganado}}</b></li>
          <li>Cantidad de Combates Ganados por KO: <b class="text-primary">{{boxeador.record.ganado_ko}}</b></li>
          <li> Cantidad de Combates Empatados: <b class="text-warning">{{boxeador.record.empate}}</b></li>
          <li>Cantidad de Combates Perdidos: <b class="text-danger">{{boxeador.record.perdido}}</b></li>
          <li>Cantidad de Combates Perdidos por KO: <b class="text-danger">{{boxeador.record.perdido_ko}}</b></li>
        </ul>
      </div>
      <div class="col-md-4 mx-auto">
        <img class="float-right img-fluid imagenTam imagen" src="{{boxeador.imagen.url}}" alt="Cinque Terre">

      </div>
    </div>
    <br>
    
    <table class="table table-condensed">
      <thead>
          <th>Fecha</th>
          <th>Categoria</th>
          <th>Luchador</th>
          <th>Oponente</th>
      </thead>
      <tbody>
        {% for c in boxeador.lista_combates %}
              <tr>
                  <td> {{c.fecha}}</td>

                  <td> {{c.categoria}}</td>

                  <td>{{c.luchador.apellido}} {{c.luchador.nombre}}
                    {% if c.ganador.id == c.luchador.id %}
                      <i class="fas fa-trophy text-warning"></i>
                    {% endif %}
                  </td>

                  <td> {{c.oponente.apellido}} {{c.oponente.nombre}}
                    {% if c.ganador.id == c.oponente.id %}
                        <i class="fas fa-trophy text-warning"></i>
                    {% endif %}
                  </td>

              </tr>
          {% endfor %}
      </tbody>
  </table>
  
  <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-sm btn-outline-secondary mb-2 float-right">Volver a La Página Anterior</a>

  </div>

</main>
{% include "centro/modal.html" %}
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function() {

  $(".modificar-modal").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
    });

});
</script>
{% endblock %}

boxeadores/templates/boxeadores/boxeador_list.html
{% extends 'centro/base.html' %}
{% block title %} {{titulo}} {% endblock %}
{% block contenido %}
<main role="main">
<div class="container-fluid">
    <h4 class="text-center">Boxeadores</h4>
    <p class="text-center">Los Resultados del Mundo de Box</p>

    <!-- Inicio Formulario  -->

    <div class="col-md-12 col-md-offset-2">
      <form class="form-inline" action="">
        <input type="text" class="form-control form-control-sm mb-2 col-md-2" placeholder="Ingresar Alias, Nombre o Apellido" name="texto" value="{{texto}}">
        <label for="pwd" class="col-md-1">Categoria:</label>
        <select name="categoria" id="" class="form-control form-control-sm mb-2 col-md-2">
          <option value="0">TODOS***</option>
            {% for cat in categorias %}
                <option value="{{cat.id}}" {% if cat.id == categoria %} selected {%endif%}>
                  {{cat.nombre}}
                </option>
            {% endfor %}
        </select>

        <label for="estado" class="col-md-1">Estado:</label>
        <select name="estado" id="estado" class="form-control form-control-sm mb-2 input-sm col-md-2 ">
            <option value="">TODOS***</option>
            {% for key, value in estados %}
                <option value="{{key}}" {% if key == estado %}selected{%endif%}>{{value}}</option>
            {% endfor %}
        </select>

        <div class=" col-md-2">
          <button type="submit" class="btn btn-outline-warning btn-sm mb-2">Buscar</button>
        </div>
        {% if perms.boxeadores.add_boxeador %}
          <div style="float: right" > <!--Aqui debe ir una funcion de boostrap ... ¡buscar! -->
            <button class="agregar-modal btn btn-sm btn-outline-danger mb-2" type="button" name="button">Agregar un Nuevo Boxeador</button>
          </div>
        {% endif %}

      </form>
      </div>
      </div>

    <!-- Inicio Tabla -->

    <div class="container-fluid mt-4">
        <table class="table table-condensed">
            <thead>
              <th>Apellido y Nombre</th>
              <th>Alias</th>
              <th>Peleas</th>
              <th>Acciones</th>
            </thead>
            <tbody>
              {% for boxeador in object_list %}
                <tr>
                  <td> {{boxeador.apellido}} {{boxeador.nombre}}</td>
                  <td>{{boxeador.alias}}</td>
                  <td>
                    <b class="text-primary" data-toggle="tooltip" data-placement="top" title="Combates ganados por KO {{boxeador.record.ganado_ko}}">{{boxeador.record.ganado}}</b>
                     | <b class="text-warning" data-toggle="tooltip" data-placement="top" title="Combates Empatados">{{boxeador.record.empate}}</b>
                     | <b class="text-danger" data-toggle="tooltip" data-placement="top" title="Combates Perdidos por KO {{boxeador.record.perdido_ko}}">{{boxeador.record.perdido}}</b>

                  </td>
                  <td>
                    <a class="accion text-dark" href="{% url 'boxeadores:ver' boxeador.id %}" title="Ver detalle de {{boxeador.alias}}"><i class="fas fa-search"></i></a>
                    {% if perms.boxeadores.change_boxeador %}
                    |
                    <a class="modificar-modal accion text-dark" title="Modificar datos de {{boxeador.alias}}" data-id="{%url 'boxeadores:modifica' boxeador.id %}">
                        <i class="fas fa-pen"></i>
                    </a>
                    {%endif%}
                    {% if perms.boxeadores.delete_boxeador %}
                    |
                    <a class="eliminar-modal accion text-danger" title="Eliminar Boxeador" data-id="{% url 'boxeadores:eliminar' boxeador.id %}">
                      <i class="fas fa-trash-alt"></i>
                    </a>
                    {%endif%}

                  </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>


    <!-- Paginación -->
  <br>
{% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&laquo;</a>
        </li>
      {% endif %}
      {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %}">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&raquo;</a>
        </li>
      {% endif %}
    </ul>
  </nav>

</main>
{% endif %}

{% include "centro/modal.html" %}
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(document).ready(function() {

  $(".agregar-modal").modalForm({
        formURL: "{% url 'boxeadores:alta' %}"
    });

  $(".modificar-modal").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
    });

  $(".eliminar-modal").each(function () {
        $(this).modalForm({formURL: $(this).data('id')});
    });
});
</script>
{% endblock %}

boxeadores/templates/boxeadores/categoria_form.html
{% extends 'centro/base.html' %}
{% load static %}

{% block contenido %}
{% include 'combates/includes/ckeditor.html' %}
<div class="container">
  <div class="row mt-3 mb-5">
    <div class="col-md-9 mx-auto">
        <div class="md-form">
              
      <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        
        {% for error in form.non_field_errors%}
          <div class="alert alert-danger" role="alert">
                {{error}}
          </div>
        {% endfor%}

        {% for field in form  %}
                <div class="form-group col-md-12">
                    {% if field.errors %}
                        <div class="control-group has-error">
                            <label class="control-label"> {{field.label}} </label>
                                <div class="controls"> {{ field }}
                                    <span class="help-block">
                                        {% for error in  field.errors %}{{ error }}{% endfor %}
                                </span>
                            </div>
                        </div>
                    {% else %}
                        <div class="control-group">
                            <label class="control-label">{{field.label}}</label>
                            <div class="controls">{{field}}
                                {% if field.help_text %}
                                    <p class="help-block"><small>{{ field.help_text }}</small></p>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
        {% endfor  %}  
        <div class="col-md-12">
            <div class="float-right mt-2">
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-sm btn-secondary">Cancelar</a>
                <input type="submit" class="btn btn-primary btn-sm text-rigth" value="Guardar" />
            </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock contenido %}