blogs/urls.py
from django.urls import path
from .views import PostListView, PostCreateView, PostDetailView, PostUpdateView

blogs_patterns = ([
    path('', PostListView.as_view(), name='posts'),
    path('create/<int:combate>', PostCreateView.as_view(), name='create'),
    path('<slug:slug>/', PostDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', PostUpdateView.as_view(), name='update'),
], 'blogs')

combates/urls.py
from django.urls import path
from .views import CombateListView, CombateCreateView, CombateDetailView, CombateUpdateView

combates_patterns = ([
    path('', CombateListView.as_view(), name='combates'),
    path('alta', CombateCreateView. as_view(), name='alta'),
    path('modifica/<int:pk>/', CombateUpdateView.as_view(), name='modifica'),
    path('ver/<int:pk>/', CombateDetailView.as_view(), name='ver'),
], 'combates')

elRing/urls.py
from django.contrib import admin
from django.urls import path, include
from boxeadores.urls import boxeadores_patterns, asociaciones_patterns, categorias_patterns
from combates.urls import combates_patterns
from profiles.urls import profiles_patterns
from blogs.urls import blogs_patterns
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('centro.urls')),
    path('boxeadores/', include(boxeadores_patterns)),
    path('combates/', include(combates_patterns)),
    path('profiles/', include(profiles_patterns)),
    path('asociaciones/', include(asociaciones_patterns)),
    path('categorias/', include(categorias_patterns)),
    path('blogs/', include(blogs_patterns)),
    

    # Autenticacion
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

combates/models.py
from django.db import models
from boxeadores.models import Boxeador, Categoria
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User


class Combate(models.Model):
    luchador = models.ForeignKey(
        Boxeador,
        related_name="Luchador",
        null=True,
        blank=True,
        on_delete=models.CASCADE)

    oponente = models.ForeignKey(
        'boxeadores.Boxeador',
        related_name="Oponente",
        null=True,
        blank=True,
        on_delete=models.CASCADE)

    fecha = models.DateTimeField()

    ganador = models.ForeignKey(
        Boxeador,
        related_name="Ganador",
        null=True,
        blank=True,
        on_delete=models.CASCADE)

    knockout = models.BooleanField(default=False)

    resumen = RichTextField(null=True, blank=True)
    empate = models.BooleanField(default=False)
    categoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE)

    user_create = models.ForeignKey(
        User, 
        related_name="UserCreate",
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    user_update = models.ForeignKey(
        User,
        related_name="UserUpdate",
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )


    class Meta:
        ordering = ['-fecha']


# Create your models here.

combates/forms.py
from django import forms
from .models import Combate


class CombateForm(forms.ModelForm):
    class Meta:
        model = Combate
        fields = (
            'luchador',
            'oponente',
            'categoria',
            'fecha',
            'resumen',
            'ganador',
            'knockout',
            'empate')

        widgets = {
            'luchador': forms.Select(attrs={"class": "form-control", "title": "Cargar el Luchador"}),
            'oponente': forms.Select(attrs={"class": "form-control", "title": "Cargar el Oponente"}),
            'fecha': forms.DateInput(attrs={"class": "form-control input-sm", "type": "date"},
                format="%Y-%m-%d",),
            'resumen': forms.Textarea(
                attrs={"class": "form-control input-sm"}
            ),

            'ganador': forms.Select(attrs={"class": "form-control"}),
            'categoria': forms.Select(attrs={"class": "form-control", "title": "Cargar Categoria"}),
        }

        labels = {
            'luchador': 'Luchador:',
            'oponente': 'Oponente:',
            'fecha': 'Fecha del Combate',
            'resumen': 'Resúmen:',
            'categoria': 'Categoria:',
            'ganador': 'Ganador:',
            'empate': 'Empate'
        }

    def clean(self):
        cleaned_data = super().clean()
        oponente = self.cleaned_data.get("oponente")
        luchador = self.cleaned_data.get("luchador")
        ganador = self.cleaned_data.get("ganador")
        empate = self.cleaned_data.get("empate")
        knockout = self.cleaned_data.get("knockout")
        
        if luchador == oponente:
            raise forms.ValidationError("El Oponente debe ser diferente al Luchador.")
        elif (luchador != ganador) and (oponente != ganador) and (empate is not True):
            raise forms.ValidationError("El ganador no puede ser distinto a uno de los contendientes")
        if empate and ganador:
            raise forms.ValidationError("No Puede haber un ganador y a la vez un empate, destildar el check de Empate")
        if knockout and empate:
            raise forms.ValidationError("No Puede haber un ganador por Knockout y a la vez un Empate")
        if luchador.genero != oponente.genero:
            raise forms.ValidationError("Acaba de Seleccionar Boxeadores de Distinto Sexo")
        return cleaned_data

combates/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from .forms import CombateForm
from .models import Combate
from boxeadores.models import ESTADO, Categoria, Record
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required, permission_required


class CombateListView(ListView):
    model = Combate
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['estados'] = ESTADO
        context['categorias'] = Categoria.objects.values()
        context['categoria'] = int(self.request.GET.get('categoria', '0'))
        return context

    def get_queryset(self):
        estado = self.request.GET.get('estado', '')
        categoria = self.request.GET.get('categoria', '0')
        combates = super().get_queryset().select_related('categoria','ganador','luchador','oponente')
        if categoria != '0':
            combates = combates.filter(categoria_id=categoria)
            # Falta filtrar por Estado
        return combates


class CombateDetailView(DetailView):
    model = Combate

    
class CombateCreateView(SuccessMessageMixin, CreateView):
    model = Combate
    form_class = CombateForm
    success_url = reverse_lazy('combates:combates')
    success_message = "Datos guardados exitosamente."


    @method_decorator(login_required())
    @method_decorator(permission_required('combates.add_combate', reverse_lazy('home')))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = 'Combate'
        return context

    
    def form_valid(self, form):
        c = form.save(commit=False)
        luchador = form.cleaned_data['luchador'].id
        oponente = form.cleaned_data['oponente'].id
        ganador = form.cleaned_data['ganador']
        ko = form.cleaned_data['knockout']
        empate = form.cleaned_data['empate']
        c.user_create = self.request.user
        Record().alta(luchador,ko,ganador,empate)
        Record().alta(oponente,ko, ganador, empate)
        return super().form_valid(form)


class CombateUpdateView(SuccessMessageMixin, UpdateView):
    model = Combate
    form_class = CombateForm
    success_url = reverse_lazy('combates:combates')
    success_messag = "Datos guardados exitosamente."

    @method_decorator(login_required())
    @method_decorator(permission_required('combates.add_combate', reverse_lazy('home')))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        combate = self.get_object()
        c = form.save(commit=False)
        oponente = form.cleaned_data['oponente'].id
        ganador = form.cleaned_data['ganador']
        ko = form.cleaned_data['knockout']
        luchador = form.cleaned_data['luchador'].id
        empate = form.cleaned_data['empate']
        c.user_update = self.request.user
        Record().baja(combate.luchador, combate.knockout, combate.ganador, combate.empate)
        Record().baja(combate.oponente, combate.knockout, combate.ganador, combate.empate)
        Record().alta(luchador,ko,ganador,empate)
        Record().alta(oponente,ko, ganador, empate)
        return super().form_valid(form)


# Create your views here.

combates/templates/combates/combate_detail.html
{% extends 'centro/base.html' %}
{% load static %}

{% block title %} {{titulo}} {% endblock title %}

{% block contenido %}
<main class="main">
    <div class="container-fluid">
    <h4 class="text-center mb-3">Fecha del Combate: {{object.fecha | date:"d-m-Y"}}</h4>
        <div class="row" style="margin-bottom: 30px;">
            <div class="col-md-2">
                
                <a href="{% url 'boxeadores:ver' combate.luchador.id %}">
                    <img class="img-fluid imagen" src="{{combate.luchador.imagen.url}}" alt="">
                </a>
                
            </div>
            <div class="col-md-4">
                <ul class="list-unstyled">
                    <li><b>Apellido y Nombre: </b>{{combate.luchador.apellido}} {{combate.luchador.nombre}}</li>
                    <li><b>Cantidad de Combates: </b><b class="text-success"> {{combate.luchador.record.total}}</b></li>
                    <li><b>Cantidad de Combates Ganados: </b><b class="text-primary">{{combate.luchador.record.ganado}}</b>
                        {% if combate.ganador.id == combate.luchador.id %}
                            <i class="fas fa-trophy text-warning"></i>
                        {% endif %}
                    </li>
                    <li><b>Cantidad de Combates Perdidos: </b><b class="text-danger">{{combate.luchador.record.perdido}}</b></li>
                </ul>
            </div>
            <div class="col-md-4">
                <ul class="list-unstyled">
                    <li><b>Apellido y Nombre: </b>{{combate.oponente.apellido}} {{combate.oponente.nombre}}</li>
                    <li><b>Cantidad de Combates:</b><b class="text-success"> {{combate.oponente.record.total}}</b></li>
                    <li><b>Cantidad de Combates Ganados: </b><b class="text-primary">{{combate.oponente.record.ganado}}</b>
                        {% if combate.ganador.id == combate.oponente.id %}
                            <i class="fas fa-trophy text-warning"></i>
                        {% endif %}
                    </li>
                    <li><b>Cantidad de Combates Perdidos: </b><b class="text-danger">{{combate.oponente.record.perdido}}</b></li>
                </ul>
            </div>
            <div class="col-md-2">
                <a href="{% url 'boxeadores:ver' combate.oponente.id %}">
                <img class="img-fluid"  src="{{combate.oponente.imagen.url}}" alt="" title='Ver Record de {{combate.oponente.alias}}'>
                </a>
            </div>
        </div>
        
        {% if perms.combates.change_combate %}
        <a href="{% url 'combates:modifica' combate.id%}">Modificar</a> |
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'blogs:create' combate.id %}">Comentar</a> |
        {% endif %}
        <a href="{% url 'blogs:posts'%}?id={{combate.id}}">Ver Comentarios</a>
        <hr>
        {% if combate.resumen %}
        <div class="row">
            <div class="col-md-1"></div>
            <div class="col-md-10">
                <p class="text-center">{{combate.resumen|safe}}</p>
            </div>
            <div class="col-md-1"></div>
        </div>
        <hr>    
        {% endif %}
        
        <div class="row">
                <div class="col-md-12">
                    <h3 class="text-center">Ultimos Combates</h3>
                </div>
                <div class="col-md-6">
                    <table class="table table-condensed mr-4" style="font-size: 14px;">
                    <thead>
                        <tr>
                            <th>Fecha</th>
                            <th>Categoria</th>
                            <th>Luchador</th>
                            <th>Oponente</th>
                            <th></th>
                        </tr>
                    </thead>
                    <body>
                        {% for c in combate.luchador.last_five_fights %}
                            <tr>
                                <td> {{c.fecha | date:"d-m-Y"}}</td>
                                <td> {{c.categoria}}</td>
                                <td>{{c.luchador.apellido}} {{c.luchador.nombre}}
                                {% if c.ganador.id == c.luchador.id %}
                                    <i class="fas fa-trophy text-warning"></i>
                                {% endif %}
                                </td>
                                <td> {{c.oponente.apellido}} {{c.oponente.nombre}}
                                {% if c.ganador.id == c.oponente.id %}
                                    <i class="fas fa-trophy text-warning"></i>
                                {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'combates:ver' c.id %}">ver mas...</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </body>
                </table>

                </div>

                <div class="col-md-6">
                    <table class="table table-condensed ml-4" style="font-size: 14px;">
                        <thead>
                            <tr>
                                <th>Fecha</th>
                                <th>Categoria</th>
                                <th>Luchador</th>
                                <th>Oponente</th>
                                <th></th>
                                
                            </tr>
                        </thead>
                        <body>
                            {% for c in combate.oponente.last_five_fights %}
                            <tr>
                                <td> {{c.fecha | date:"d-m-Y"}}</td>
                                <td> {{c.categoria}}</td>
                                <td>{{c.luchador.apellido}} {{c.luchador.nombre}}
                                    {% if c.ganador.id == c.luchador.id %}
                                        <i class="fas fa-trophy text-warning"></i>
                                    {% endif %}
                                </td>
                                <td> {{c.oponente.apellido}} {{c.oponente.nombre}}
                                {% if c.ganador.id == c.oponente.id %}
                                    <i class="fas fa-trophy text-warning"></i>
                                {% endif %}
                                </td>
                                <td>
                                    <a href="{% url 'combates:ver' c.id %}">ver mas...</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </body>
                    </table>
                </div>
            </div>
    </div>
</main>
{% endblock %}

combates/templates/combates/combate_form.html
{% extends 'centro/base.html' %}
{% load static %}

{% block contenido %}
{% include 'combates/includes/ckeditor.html' %}
<div class="container">
  <div class="row mt-3 mb-5">
    <div class="col-md-9 mx-auto">
        <div class="md-form">
              
      <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
        
        {% for error in form.non_field_errors%}
          <div class="alert alert-danger" role="alert">
                {{error}}
          </div>
        {% endfor%}

        {% for field in form  %}
            {% if field == form.luchador %}
                <div class="form-group col-md-12 {% if form.luchador.errors %} invalid has-error {% endif %}">
                    <label for="{{ form.luchador.id_for_label }}" class="control-label">{{ form.luchador.label }}</label>
                    <input autofocus type="search" id="search" class="form-control" 
                    value="{% if form.instance.luchador %} {{form.instance.luchador}} {% endif %}">
                    <input type="hidden" id="luchador" name="luchador" value="{{form.instance.luchador.id}}">
                    {% for error in form.luchador.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </div>
            {% elif field == form.oponente %} 
                <div class="form-group col-md-12 {% if form.oponente.errors %} invalid has-error {% endif %}">
                    <label for="{{ form.oponente.id_for_label }}" class="control-label">{{ form.oponente.label }}</label>
                    <input autofocus type="search" id="search-oponente" class="form-control" 
                    value="{% if form.instance.oponente %} {{form.instance.oponente}} {% endif %}">
                    <input type="hidden" id="oponente" name="oponente" value="{{form.instance.oponente.id}}">
                        {% for error in form.oponente.errors %}
                            <p class="help-block">{{ error }}</p>
                        {% endfor %}
                </div>

            {% elif field == form.ganador %} 
                <div class="form-group col-md-12 {% if form.ganador.errors %} invalid has-error {% endif %}">
                    <label for="{{ form.ganador.id_for_label }}" class="control-label">{{ form.ganador.label }}</label>
                    <input autofocus type="search" id="search-ganador" class="form-control" 
                    value="{% if form.instance.ganador %} {{form.instance.ganador}} {% endif %}">
                    <input type="hidden" id="ganador" name="ganador" value="{{form.instance.ganador.id}}">
                        {% for error in form.ganador.errors %}
                            <p class="help-block">{{ error }}</p>
                        {% endfor %}
                </div>

            {% elif field == form.empate or field == form.knockout%} 
                <div class="form-check">
                {% if field.errors %}
                    <div class="control-group has-error">
                        <label class="control-label"> {{field.label}} </label>
                            <div class="controls"> {{ field }}
                                <span class="help-block">
                                    {% for error in  field.errors %}{{ error }}{% endfor %}
                            </span>
                        </div>
                    </div>
                {% else %}
        
                    {{field}}
                    <label class="form-check-label">{{field.label}}</label>
                        {% if field.help_text %}
                            <p class="help-block"><small>{{ field.help_text }}</small></p>
                        {% endif %}
                    
                {% endif %}
            </div>
            

            {% else %}
                <div class="form-group col-md-12">
                    {% if field.errors %}
                        <div class="control-group has-error">
                            <label class="control-label"> {{field.label}} </label>
                                <div class="controls"> {{ field }}
                                    <span class="help-block">
                                        {% for error in  field.errors %}{{ error }}{% endfor %}
                                </span>
                            </div>
                        </div>
                    {% else %}
                        <div class="control-group">
                            <label class="control-label">{{field.label}}</label>
                            <div class="controls">{{field}}
                                {% if field.help_text %}
                                    <p class="help-block"><small>{{ field.help_text }}</small></p>
                                {% endif %}
                            </div>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor  %}  
        <div class="col-md-12">
            <div class="float-right mt-2">
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-sm btn-secondary">Cancelar</a>
                <input type="submit" class="btn btn-primary btn-sm text-rigth" value="Guardar" />
            </div>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock contenido %}

{% block scripts %}
  <script>
    $(document).ready(function(){
      $("#search").autocomplete({
            source: function(request, response) {
                let term = $("#search").val();
                $.ajax({
                    dataType: "json",
                    type: 'GET',
                    data: {'term': term},
                    url: "{% url 'boxeadores:buscar'%}",
                    success: function (data) {
                        response(data);
                        if (data == "") {
                            $("#luchador").val("");
                        }
                    },
                });
            },
            minLength: 3,
            delay: 500,
            select: function(event, ui) {
                console.log(ui);
                $("#luchador").val(ui.item.id);
            },
        });
  } );
</script>
<script>
  $(document).ready(function(){
    $("#search-oponente").autocomplete({
            source: function(request, response) {
                let term = $("#search-oponente").val();
                $.ajax({
                    dataType: "json",
                    type: 'GET',
                    data: {'term': term},
                    url: "{% url 'boxeadores:buscar'%}",
                    success: function (data) {
                        response(data);
                        if (data == "") {
                            $("#oponente").val("");
                        }
                    },
                });
            },
            minLength: 3,
            delay: 500,
            select: function(event, ui) {
                $("#oponente").val(ui.item.id);
            },
        });
  });
</script>
<script>
  $(document).ready(function(){
    $("#search-ganador").autocomplete({
            source: function(request, response) {
                let term = $("#search-ganador").val();
                $.ajax({
                    dataType: "json",
                    type: 'GET',
                    data: {'term': term},
                    url: "{% url 'boxeadores:buscar'%}",
                    success: function (data) {
                        response(data);
                        if (data == "") {
                            $("#ganador").val("");
                        }
                    },
                });
            },
            minLength: 3,
            delay: 500,
            select: function(event, ui) {
                $("#ganador").val(ui.item.id);
            },
        });
  });
</script>
{% endblock scripts %}

combates/templates/combates/combate_list.html
{% extends 'centro/base.html' %}
{% load static %}
{% block title %}Combates{% endblock %}
{% block contenido %}
<main role="main">
<div class="container-fluid">
    <h4 class="text-center">Combates</h4>
    <p class="text-center">Los Resultados del Mundo de Box</p>
    
    <div class="col-md-12 col-md-offset-2">
      <form class="form-inline" action="">
        <label for="pwd" class="col-md-1">Categoria:</label>              
        <select name="categoria" id="" class="form-control form-control-sm mb-2 col-md-2">
          <option value="0">TODOS***</option>
            {% for cat in categorias %}
                <option value="{{cat.id}}" {% if cat.id == categoria %} selected {%endif%}>
                  {{cat.nombre}}
                </option>
            {% endfor %}
        </select>
        
        <label for="estado" class="col-md-1">Estado:</label>
        <select name="estado" id="estado" class="form-control form-control-sm mb-2 input-sm col-md-2 ">
            <option value="0">TODOS***</option>
            {% for key, value in estados %}
                <option value="{{key}}" {% if key == estado %}selected{%endif%}>{{value}}</option>
            {% endfor %}
        </select>
        
        <div class=" col-md-4">
          <button type="submit" class="btn btn-outline-warning btn-sm mb-2 col-md-2">Buscar</button>
        </div>
        {% if perms.combates.add_combate %}
          <div style="float: right" > <!--Aqui debe ir una funcion de boostrap ... ¡buscar! -->
            <a href="{% url 'combates:alta' %}" class="btn btn-sm btn-outline-danger mb-2">Agregar un Nuevo Combate</a>
          </div>
        {%endif%}
      </form> 
      </div>

    <table class="table table-condensed mt-4">
      <thead>
          <th>Fecha</th>
          <th>Categoria</th>
          <th>Luchador</th>
          <th>Oponente</th>
          <th></th>
      </thead>
      <tbody>
        {% for c in object_list %}
          <tr>
            <td> {{c.fecha | date:"d-m-Y"}}</td>
            <td> {{c.categoria}}</td>
            <td>{{c.luchador.apellido}} {{c.luchador.nombre}}
              {% if c.ganador.id == c.luchador.id %}
              <i class="fas fa-trophy text-warning"></i>
              {% endif %}
            </td>
            <td> {{c.oponente.apellido}} {{c.oponente.nombre}}
            {% if c.ganador.id == c.oponente.id %}
              <i class="fas fa-trophy text-warning"></i>
            {% endif %}
            </td>
            <td> 
              <a href="{% url 'combates:ver' c.id %}">ver mas...</a>
            </td>      
          </tr>
        {% endfor %}
      </tbody>
  </table>


  <!-- Paginación -->
  <br>
  {% if is_paginated %}
  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-end">
      {% if page_obj.has_previous %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&laquo;</a>
        </li>
      {% endif %}
      {% for i in paginator.page_range %}
        <li class="page-item {% if page_obj.number == i %}active{% endif %}">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item ">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link" href="#" tabindex="-1">&raquo;</a>
        </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}

</div>
</main>
{% endblock %}


{% block scripts %}
{% endblock scripts %}
  